const bio = {
    "login": "thevetdoctor",
    "id": 13197630,
    "node_id": "MDQ6VXNlcjEzMTk3NjMw",
    "avatar_url": "https://avatars.githubusercontent.com/u/13197630?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/thevetdoctor",
    "html_url": "https://github.com/thevetdoctor",
    "followers_url": "https://api.github.com/users/thevetdoctor/followers",
    "following_url": "https://api.github.com/users/thevetdoctor/following{/other_user}",
    "gists_url": "https://api.github.com/users/thevetdoctor/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/thevetdoctor/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/thevetdoctor/subscriptions",
    "organizations_url": "https://api.github.com/users/thevetdoctor/orgs",
    "repos_url": "https://api.github.com/users/thevetdoctor/repos",
    "events_url": "https://api.github.com/users/thevetdoctor/events{/privacy}",
    "received_events_url": "https://api.github.com/users/thevetdoctor/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Obafemi",
    "company": "Animalworld NG",
    "blog": "https://www.linkedin.com/in/obafemi-oderanti",
    "location": "Nigeria",
    "email": null,
    "hireable": true,
    "bio": "Fullstack Software Engineer:: Andela > Facebook > Google > Enye > Scello ::\r\nI love building solutions!",
    "twitter_username": "animalworldng",
    "public_repos": 150,
    "public_gists": 1,
    "followers": 21,
    "following": 68,
    "created_at": "2015-07-06T09:22:53Z",
    "updated_at": "2021-07-21T08:20:28Z"
  }

  export default bio;