const following = [
    {
      "login": "phpwax",
      "id": 5098,
      "node_id": "MDQ6VXNlcjUwOTg=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5098?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/phpwax",
      "html_url": "https://github.com/phpwax",
      "followers_url": "https://api.github.com/users/phpwax/followers",
      "following_url": "https://api.github.com/users/phpwax/following{/other_user}",
      "gists_url": "https://api.github.com/users/phpwax/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/phpwax/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/phpwax/subscriptions",
      "organizations_url": "https://api.github.com/users/phpwax/orgs",
      "repos_url": "https://api.github.com/users/phpwax/repos",
      "events_url": "https://api.github.com/users/phpwax/events{/privacy}",
      "received_events_url": "https://api.github.com/users/phpwax/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "przeor",
      "id": 5995,
      "node_id": "MDQ6VXNlcjU5OTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5995?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/przeor",
      "html_url": "https://github.com/przeor",
      "followers_url": "https://api.github.com/users/przeor/followers",
      "following_url": "https://api.github.com/users/przeor/following{/other_user}",
      "gists_url": "https://api.github.com/users/przeor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/przeor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/przeor/subscriptions",
      "organizations_url": "https://api.github.com/users/przeor/orgs",
      "repos_url": "https://api.github.com/users/przeor/repos",
      "events_url": "https://api.github.com/users/przeor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/przeor/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "jerone",
      "id": 55841,
      "node_id": "MDQ6VXNlcjU1ODQx",
      "avatar_url": "https://avatars.githubusercontent.com/u/55841?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jerone",
      "html_url": "https://github.com/jerone",
      "followers_url": "https://api.github.com/users/jerone/followers",
      "following_url": "https://api.github.com/users/jerone/following{/other_user}",
      "gists_url": "https://api.github.com/users/jerone/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jerone/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jerone/subscriptions",
      "organizations_url": "https://api.github.com/users/jerone/orgs",
      "repos_url": "https://api.github.com/users/jerone/repos",
      "events_url": "https://api.github.com/users/jerone/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jerone/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "jakearchibald",
      "id": 93594,
      "node_id": "MDQ6VXNlcjkzNTk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/93594?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/jakearchibald",
      "html_url": "https://github.com/jakearchibald",
      "followers_url": "https://api.github.com/users/jakearchibald/followers",
      "following_url": "https://api.github.com/users/jakearchibald/following{/other_user}",
      "gists_url": "https://api.github.com/users/jakearchibald/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/jakearchibald/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/jakearchibald/subscriptions",
      "organizations_url": "https://api.github.com/users/jakearchibald/orgs",
      "repos_url": "https://api.github.com/users/jakearchibald/repos",
      "events_url": "https://api.github.com/users/jakearchibald/events{/privacy}",
      "received_events_url": "https://api.github.com/users/jakearchibald/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "keithamus",
      "id": 118266,
      "node_id": "MDQ6VXNlcjExODI2Ng==",
      "avatar_url": "https://avatars.githubusercontent.com/u/118266?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/keithamus",
      "html_url": "https://github.com/keithamus",
      "followers_url": "https://api.github.com/users/keithamus/followers",
      "following_url": "https://api.github.com/users/keithamus/following{/other_user}",
      "gists_url": "https://api.github.com/users/keithamus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/keithamus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/keithamus/subscriptions",
      "organizations_url": "https://api.github.com/users/keithamus/orgs",
      "repos_url": "https://api.github.com/users/keithamus/repos",
      "events_url": "https://api.github.com/users/keithamus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/keithamus/received_events",
      "type": "User",
      "site_admin": true
    },
    {
      "login": "sindresorhus",
      "id": 170270,
      "node_id": "MDQ6VXNlcjE3MDI3MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/170270?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/sindresorhus",
      "html_url": "https://github.com/sindresorhus",
      "followers_url": "https://api.github.com/users/sindresorhus/followers",
      "following_url": "https://api.github.com/users/sindresorhus/following{/other_user}",
      "gists_url": "https://api.github.com/users/sindresorhus/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/sindresorhus/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/sindresorhus/subscriptions",
      "organizations_url": "https://api.github.com/users/sindresorhus/orgs",
      "repos_url": "https://api.github.com/users/sindresorhus/repos",
      "events_url": "https://api.github.com/users/sindresorhus/events{/privacy}",
      "received_events_url": "https://api.github.com/users/sindresorhus/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "myquery",
      "id": 349462,
      "node_id": "MDQ6VXNlcjM0OTQ2Mg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/349462?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/myquery",
      "html_url": "https://github.com/myquery",
      "followers_url": "https://api.github.com/users/myquery/followers",
      "following_url": "https://api.github.com/users/myquery/following{/other_user}",
      "gists_url": "https://api.github.com/users/myquery/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/myquery/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/myquery/subscriptions",
      "organizations_url": "https://api.github.com/users/myquery/orgs",
      "repos_url": "https://api.github.com/users/myquery/repos",
      "events_url": "https://api.github.com/users/myquery/events{/privacy}",
      "received_events_url": "https://api.github.com/users/myquery/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "timcheadle",
      "id": 612212,
      "node_id": "MDQ6VXNlcjYxMjIxMg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/612212?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/timcheadle",
      "html_url": "https://github.com/timcheadle",
      "followers_url": "https://api.github.com/users/timcheadle/followers",
      "following_url": "https://api.github.com/users/timcheadle/following{/other_user}",
      "gists_url": "https://api.github.com/users/timcheadle/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/timcheadle/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/timcheadle/subscriptions",
      "organizations_url": "https://api.github.com/users/timcheadle/orgs",
      "repos_url": "https://api.github.com/users/timcheadle/repos",
      "events_url": "https://api.github.com/users/timcheadle/events{/privacy}",
      "received_events_url": "https://api.github.com/users/timcheadle/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "giuseppeg",
      "id": 711311,
      "node_id": "MDQ6VXNlcjcxMTMxMQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/711311?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/giuseppeg",
      "html_url": "https://github.com/giuseppeg",
      "followers_url": "https://api.github.com/users/giuseppeg/followers",
      "following_url": "https://api.github.com/users/giuseppeg/following{/other_user}",
      "gists_url": "https://api.github.com/users/giuseppeg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/giuseppeg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/giuseppeg/subscriptions",
      "organizations_url": "https://api.github.com/users/giuseppeg/orgs",
      "repos_url": "https://api.github.com/users/giuseppeg/repos",
      "events_url": "https://api.github.com/users/giuseppeg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/giuseppeg/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "liu21st",
      "id": 1111670,
      "node_id": "MDQ6VXNlcjExMTE2NzA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1111670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/liu21st",
      "html_url": "https://github.com/liu21st",
      "followers_url": "https://api.github.com/users/liu21st/followers",
      "following_url": "https://api.github.com/users/liu21st/following{/other_user}",
      "gists_url": "https://api.github.com/users/liu21st/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/liu21st/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/liu21st/subscriptions",
      "organizations_url": "https://api.github.com/users/liu21st/orgs",
      "repos_url": "https://api.github.com/users/liu21st/repos",
      "events_url": "https://api.github.com/users/liu21st/events{/privacy}",
      "received_events_url": "https://api.github.com/users/liu21st/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "csev",
      "id": 1197222,
      "node_id": "MDQ6VXNlcjExOTcyMjI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1197222?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/csev",
      "html_url": "https://github.com/csev",
      "followers_url": "https://api.github.com/users/csev/followers",
      "following_url": "https://api.github.com/users/csev/following{/other_user}",
      "gists_url": "https://api.github.com/users/csev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/csev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/csev/subscriptions",
      "organizations_url": "https://api.github.com/users/csev/orgs",
      "repos_url": "https://api.github.com/users/csev/repos",
      "events_url": "https://api.github.com/users/csev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/csev/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "danprince",
      "id": 1266011,
      "node_id": "MDQ6VXNlcjEyNjYwMTE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1266011?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danprince",
      "html_url": "https://github.com/danprince",
      "followers_url": "https://api.github.com/users/danprince/followers",
      "following_url": "https://api.github.com/users/danprince/following{/other_user}",
      "gists_url": "https://api.github.com/users/danprince/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danprince/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danprince/subscriptions",
      "organizations_url": "https://api.github.com/users/danprince/orgs",
      "repos_url": "https://api.github.com/users/danprince/repos",
      "events_url": "https://api.github.com/users/danprince/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danprince/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "unicodeveloper",
      "id": 2946769,
      "node_id": "MDQ6VXNlcjI5NDY3Njk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2946769?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/unicodeveloper",
      "html_url": "https://github.com/unicodeveloper",
      "followers_url": "https://api.github.com/users/unicodeveloper/followers",
      "following_url": "https://api.github.com/users/unicodeveloper/following{/other_user}",
      "gists_url": "https://api.github.com/users/unicodeveloper/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/unicodeveloper/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/unicodeveloper/subscriptions",
      "organizations_url": "https://api.github.com/users/unicodeveloper/orgs",
      "repos_url": "https://api.github.com/users/unicodeveloper/repos",
      "events_url": "https://api.github.com/users/unicodeveloper/events{/privacy}",
      "received_events_url": "https://api.github.com/users/unicodeveloper/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "riccardonobile",
      "id": 4092574,
      "node_id": "MDQ6VXNlcjQwOTI1NzQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4092574?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/riccardonobile",
      "html_url": "https://github.com/riccardonobile",
      "followers_url": "https://api.github.com/users/riccardonobile/followers",
      "following_url": "https://api.github.com/users/riccardonobile/following{/other_user}",
      "gists_url": "https://api.github.com/users/riccardonobile/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/riccardonobile/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/riccardonobile/subscriptions",
      "organizations_url": "https://api.github.com/users/riccardonobile/orgs",
      "repos_url": "https://api.github.com/users/riccardonobile/repos",
      "events_url": "https://api.github.com/users/riccardonobile/events{/privacy}",
      "received_events_url": "https://api.github.com/users/riccardonobile/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "chenyongze",
      "id": 4531363,
      "node_id": "MDQ6VXNlcjQ1MzEzNjM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4531363?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/chenyongze",
      "html_url": "https://github.com/chenyongze",
      "followers_url": "https://api.github.com/users/chenyongze/followers",
      "following_url": "https://api.github.com/users/chenyongze/following{/other_user}",
      "gists_url": "https://api.github.com/users/chenyongze/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/chenyongze/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/chenyongze/subscriptions",
      "organizations_url": "https://api.github.com/users/chenyongze/orgs",
      "repos_url": "https://api.github.com/users/chenyongze/repos",
      "events_url": "https://api.github.com/users/chenyongze/events{/privacy}",
      "received_events_url": "https://api.github.com/users/chenyongze/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "oshadami",
      "id": 4987546,
      "node_id": "MDQ6VXNlcjQ5ODc1NDY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4987546?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/oshadami",
      "html_url": "https://github.com/oshadami",
      "followers_url": "https://api.github.com/users/oshadami/followers",
      "following_url": "https://api.github.com/users/oshadami/following{/other_user}",
      "gists_url": "https://api.github.com/users/oshadami/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/oshadami/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/oshadami/subscriptions",
      "organizations_url": "https://api.github.com/users/oshadami/orgs",
      "repos_url": "https://api.github.com/users/oshadami/repos",
      "events_url": "https://api.github.com/users/oshadami/events{/privacy}",
      "received_events_url": "https://api.github.com/users/oshadami/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "iJoshy",
      "id": 5092887,
      "node_id": "MDQ6VXNlcjUwOTI4ODc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5092887?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/iJoshy",
      "html_url": "https://github.com/iJoshy",
      "followers_url": "https://api.github.com/users/iJoshy/followers",
      "following_url": "https://api.github.com/users/iJoshy/following{/other_user}",
      "gists_url": "https://api.github.com/users/iJoshy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/iJoshy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/iJoshy/subscriptions",
      "organizations_url": "https://api.github.com/users/iJoshy/orgs",
      "repos_url": "https://api.github.com/users/iJoshy/repos",
      "events_url": "https://api.github.com/users/iJoshy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/iJoshy/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "icarlossz",
      "id": 5649014,
      "node_id": "MDQ6VXNlcjU2NDkwMTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5649014?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/icarlossz",
      "html_url": "https://github.com/icarlossz",
      "followers_url": "https://api.github.com/users/icarlossz/followers",
      "following_url": "https://api.github.com/users/icarlossz/following{/other_user}",
      "gists_url": "https://api.github.com/users/icarlossz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/icarlossz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/icarlossz/subscriptions",
      "organizations_url": "https://api.github.com/users/icarlossz/orgs",
      "repos_url": "https://api.github.com/users/icarlossz/repos",
      "events_url": "https://api.github.com/users/icarlossz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/icarlossz/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "thechinedu",
      "id": 7131935,
      "node_id": "MDQ6VXNlcjcxMzE5MzU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7131935?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/thechinedu",
      "html_url": "https://github.com/thechinedu",
      "followers_url": "https://api.github.com/users/thechinedu/followers",
      "following_url": "https://api.github.com/users/thechinedu/following{/other_user}",
      "gists_url": "https://api.github.com/users/thechinedu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/thechinedu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/thechinedu/subscriptions",
      "organizations_url": "https://api.github.com/users/thechinedu/orgs",
      "repos_url": "https://api.github.com/users/thechinedu/repos",
      "events_url": "https://api.github.com/users/thechinedu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/thechinedu/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "LearnWebCode",
      "id": 7797727,
      "node_id": "MDQ6VXNlcjc3OTc3Mjc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/7797727?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/LearnWebCode",
      "html_url": "https://github.com/LearnWebCode",
      "followers_url": "https://api.github.com/users/LearnWebCode/followers",
      "following_url": "https://api.github.com/users/LearnWebCode/following{/other_user}",
      "gists_url": "https://api.github.com/users/LearnWebCode/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/LearnWebCode/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/LearnWebCode/subscriptions",
      "organizations_url": "https://api.github.com/users/LearnWebCode/orgs",
      "repos_url": "https://api.github.com/users/LearnWebCode/repos",
      "events_url": "https://api.github.com/users/LearnWebCode/events{/privacy}",
      "received_events_url": "https://api.github.com/users/LearnWebCode/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "christiannwamba",
      "id": 8108337,
      "node_id": "MDQ6VXNlcjgxMDgzMzc=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8108337?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/christiannwamba",
      "html_url": "https://github.com/christiannwamba",
      "followers_url": "https://api.github.com/users/christiannwamba/followers",
      "following_url": "https://api.github.com/users/christiannwamba/following{/other_user}",
      "gists_url": "https://api.github.com/users/christiannwamba/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/christiannwamba/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/christiannwamba/subscriptions",
      "organizations_url": "https://api.github.com/users/christiannwamba/orgs",
      "repos_url": "https://api.github.com/users/christiannwamba/repos",
      "events_url": "https://api.github.com/users/christiannwamba/events{/privacy}",
      "received_events_url": "https://api.github.com/users/christiannwamba/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "mpaccione",
      "id": 8552642,
      "node_id": "MDQ6VXNlcjg1NTI2NDI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8552642?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mpaccione",
      "html_url": "https://github.com/mpaccione",
      "followers_url": "https://api.github.com/users/mpaccione/followers",
      "following_url": "https://api.github.com/users/mpaccione/following{/other_user}",
      "gists_url": "https://api.github.com/users/mpaccione/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mpaccione/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mpaccione/subscriptions",
      "organizations_url": "https://api.github.com/users/mpaccione/orgs",
      "repos_url": "https://api.github.com/users/mpaccione/repos",
      "events_url": "https://api.github.com/users/mpaccione/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mpaccione/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "manasehmokanya",
      "id": 8591064,
      "node_id": "MDQ6VXNlcjg1OTEwNjQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8591064?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/manasehmokanya",
      "html_url": "https://github.com/manasehmokanya",
      "followers_url": "https://api.github.com/users/manasehmokanya/followers",
      "following_url": "https://api.github.com/users/manasehmokanya/following{/other_user}",
      "gists_url": "https://api.github.com/users/manasehmokanya/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/manasehmokanya/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/manasehmokanya/subscriptions",
      "organizations_url": "https://api.github.com/users/manasehmokanya/orgs",
      "repos_url": "https://api.github.com/users/manasehmokanya/repos",
      "events_url": "https://api.github.com/users/manasehmokanya/events{/privacy}",
      "received_events_url": "https://api.github.com/users/manasehmokanya/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "ireade",
      "id": 8677283,
      "node_id": "MDQ6VXNlcjg2NzcyODM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/8677283?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ireade",
      "html_url": "https://github.com/ireade",
      "followers_url": "https://api.github.com/users/ireade/followers",
      "following_url": "https://api.github.com/users/ireade/following{/other_user}",
      "gists_url": "https://api.github.com/users/ireade/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ireade/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ireade/subscriptions",
      "organizations_url": "https://api.github.com/users/ireade/orgs",
      "repos_url": "https://api.github.com/users/ireade/repos",
      "events_url": "https://api.github.com/users/ireade/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ireade/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Gapur",
      "id": 10502684,
      "node_id": "MDQ6VXNlcjEwNTAyNjg0",
      "avatar_url": "https://avatars.githubusercontent.com/u/10502684?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Gapur",
      "html_url": "https://github.com/Gapur",
      "followers_url": "https://api.github.com/users/Gapur/followers",
      "following_url": "https://api.github.com/users/Gapur/following{/other_user}",
      "gists_url": "https://api.github.com/users/Gapur/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Gapur/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Gapur/subscriptions",
      "organizations_url": "https://api.github.com/users/Gapur/orgs",
      "repos_url": "https://api.github.com/users/Gapur/repos",
      "events_url": "https://api.github.com/users/Gapur/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Gapur/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "Monehin",
      "id": 12280033,
      "node_id": "MDQ6VXNlcjEyMjgwMDMz",
      "avatar_url": "https://avatars.githubusercontent.com/u/12280033?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Monehin",
      "html_url": "https://github.com/Monehin",
      "followers_url": "https://api.github.com/users/Monehin/followers",
      "following_url": "https://api.github.com/users/Monehin/following{/other_user}",
      "gists_url": "https://api.github.com/users/Monehin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Monehin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Monehin/subscriptions",
      "organizations_url": "https://api.github.com/users/Monehin/orgs",
      "repos_url": "https://api.github.com/users/Monehin/repos",
      "events_url": "https://api.github.com/users/Monehin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Monehin/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "emeka-osuagwu",
      "id": 13197724,
      "node_id": "MDQ6VXNlcjEzMTk3NzI0",
      "avatar_url": "https://avatars.githubusercontent.com/u/13197724?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/emeka-osuagwu",
      "html_url": "https://github.com/emeka-osuagwu",
      "followers_url": "https://api.github.com/users/emeka-osuagwu/followers",
      "following_url": "https://api.github.com/users/emeka-osuagwu/following{/other_user}",
      "gists_url": "https://api.github.com/users/emeka-osuagwu/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/emeka-osuagwu/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/emeka-osuagwu/subscriptions",
      "organizations_url": "https://api.github.com/users/emeka-osuagwu/orgs",
      "repos_url": "https://api.github.com/users/emeka-osuagwu/repos",
      "events_url": "https://api.github.com/users/emeka-osuagwu/events{/privacy}",
      "received_events_url": "https://api.github.com/users/emeka-osuagwu/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "mojibola",
      "id": 13197759,
      "node_id": "MDQ6VXNlcjEzMTk3NzU5",
      "avatar_url": "https://avatars.githubusercontent.com/u/13197759?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/mojibola",
      "html_url": "https://github.com/mojibola",
      "followers_url": "https://api.github.com/users/mojibola/followers",
      "following_url": "https://api.github.com/users/mojibola/following{/other_user}",
      "gists_url": "https://api.github.com/users/mojibola/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/mojibola/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/mojibola/subscriptions",
      "organizations_url": "https://api.github.com/users/mojibola/orgs",
      "repos_url": "https://api.github.com/users/mojibola/repos",
      "events_url": "https://api.github.com/users/mojibola/events{/privacy}",
      "received_events_url": "https://api.github.com/users/mojibola/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "i-am-deoye",
      "id": 13604550,
      "node_id": "MDQ6VXNlcjEzNjA0NTUw",
      "avatar_url": "https://avatars.githubusercontent.com/u/13604550?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/i-am-deoye",
      "html_url": "https://github.com/i-am-deoye",
      "followers_url": "https://api.github.com/users/i-am-deoye/followers",
      "following_url": "https://api.github.com/users/i-am-deoye/following{/other_user}",
      "gists_url": "https://api.github.com/users/i-am-deoye/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/i-am-deoye/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/i-am-deoye/subscriptions",
      "organizations_url": "https://api.github.com/users/i-am-deoye/orgs",
      "repos_url": "https://api.github.com/users/i-am-deoye/repos",
      "events_url": "https://api.github.com/users/i-am-deoye/events{/privacy}",
      "received_events_url": "https://api.github.com/users/i-am-deoye/received_events",
      "type": "User",
      "site_admin": false
    },
    {
      "login": "babyfaceEasy",
      "id": 16900234,
      "node_id": "MDQ6VXNlcjE2OTAwMjM0",
      "avatar_url": "https://avatars.githubusercontent.com/u/16900234?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/babyfaceEasy",
      "html_url": "https://github.com/babyfaceEasy",
      "followers_url": "https://api.github.com/users/babyfaceEasy/followers",
      "following_url": "https://api.github.com/users/babyfaceEasy/following{/other_user}",
      "gists_url": "https://api.github.com/users/babyfaceEasy/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/babyfaceEasy/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/babyfaceEasy/subscriptions",
      "organizations_url": "https://api.github.com/users/babyfaceEasy/orgs",
      "repos_url": "https://api.github.com/users/babyfaceEasy/repos",
      "events_url": "https://api.github.com/users/babyfaceEasy/events{/privacy}",
      "received_events_url": "https://api.github.com/users/babyfaceEasy/received_events",
      "type": "User",
      "site_admin": false
    }
  ];

  export default following;